spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:.env.prod[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate  # 배포 시 안전하게

server:
  port: 8080

logging:
  level:
    root: info
    est.oremi.backend12: warn
